name: '@typesafe-i18n/formatters example'

on:
   schedule:
      - cron: '0 0 * * *' # Runs everyday at 00:00
   workflow_dispatch:

defaults:
   run:
      working-directory: packages/formatters/example

jobs:
   check-formatters:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2

         - name: install node
           uses: actions/setup-node@v2
           with:
              node-version: 16.14.0

         - name: install dependencies
           run: npm install --no-save

         - name: update `typesafe-i18n` dependency
           run: npm i typesafe-i18n@latest

         - name: update all dependencies
           run: npm up

         - name: run generator
           run: npm run typesafe-i18n -- --no-watch

         - name: run TypeScript compiler
           run: tsc --noEmit

         - name: run build
           run: npm run build

         - name: Create Pull Request
           uses: peter-evans/create-pull-request@v3
           with:
              token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
              branch: update/formatters
              commit-message: 'chore: update `@typesafe-i18n/formatters` example'
              title: 'chore: update `@typesafe-i18n/formatters` example'
              body: >
                 This PR is auto-generated by a GitHub action.
