name: '@typesafe-i18n/exporter example - update dependencies'

on:
   schedule:
      - cron: '0 20 * * 0' # Runs at 20:00 on Sunday
   workflow_dispatch:

defaults:
   run:
      working-directory: packages/exporter/example

jobs:
   check-exporter:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3

         - name: install node
           uses: actions/setup-node@v2
           with:
              node-version: 18.15.0

         - name: install dependencies
           run: npm install --no-save

         - name: update all dependencies
           run: npm up

         - name: run generator
           run: npm run typesafe-i18n -- --no-watch

         - name: run TypeScript compiler
           run: tsc --noEmit

         - name: run tests
           run: npm test

         - name: Create Pull Request
           uses: peter-evans/create-pull-request@v3
           with:
              token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
              branch: update/exporter-dependencies
              commit-message: 'chore: update `@typesafe-i18n/exporter` example dependencies'
              title: 'chore: update `@typesafe-i18n/exporter` example dependencies'
              body: >
                 This PR is auto-generated by a GitHub action.
