name: '@typesafe-i18n/importer example - update to latest version'

on:
   schedule:
      - cron: '0 0 * * *' # Runs everyday at 00:00
   workflow_dispatch:

defaults:
   run:
      working-directory: packages/importer/example

jobs:
   check-importer:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3

         - name: install node
           uses: actions/setup-node@v2
           with:
              node-version: 18.15.0

         - name: install dependencies
           run: npm install --no-save

         - name: update `typesafe-i18n` dependency
           run: npm i typesafe-i18n@latest

         - name: run import
           run: npm run i18n:import

         - name: run TypeScript compiler
           run: tsc --noEmit

         - name: Create Pull Request
           uses: peter-evans/create-pull-request@v3
           with:
              token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
              branch: update/importer
              commit-message: 'chore: update `@typesafe-i18n/importer` example'
              title: 'chore: update `@typesafe-i18n/importer` example'
              body: >
                 This PR is auto-generated by a GitHub action.
